### PR TITLE
refactor documentation typo

### LINKED ISSUE #606: doxygen error
This is happening:
> Error: no ID for constraint linkend: "url.ref.boost__urls__pct_string_view.operator_star_".

### PR DESCRIPTION
**Pull request by alandefreitas**
fix #606

### CODE REVIEW

**Comment by alandefreitas** [comment]
I followed the exact instructions in `.drone/drone.sh` to install docca in clear VMs. Ubuntu 20 generates `operator__star_` and Ubuntu 22 generates `operator_star_` for some reason. 

The instructions use the exact same binaries for doxygen and saxonhe. So my guess is the versions of `xsltproc` that come with these installations are generating different outputs.

**Comment by vinniefalco** [comment]
Evan will look into this. But generally speaking, when we test with xsltproc they all need to be using the same version as what will be used to build the Boost release docs.

**Comment by evanlenz** [comment]
@alandefreitas Can you look at the contents of _classboost_1_1urls_1_1pct__string__view.xml_ (output from Doxygen)? It should be in _bin.v2/libs/url/doc/_reference-dir_.

The reason I ask is that it appears that the output of Doxygen is what will dictate whether you get one or two underscores in that page ID. I am getting the same behavior as Vinnie (two underscores), resulting from the following in that file:

```
      <memberdef kind="function" id="classboost_1_1urls_1_1pct__string__view_1ad625af7f8285fe3d9150a715111d86c3" prot="public" static="no" const="yes" explicit="no" inline="yes" virt="non-virtual">
        <type><ref refid="classboost_1_1urls_1_1decode__view" kindref="compound">decode_view</ref></type>
        <definition>decode_view boost::urls::pct_string_view::operator *</definition>
        <argsstring>() const noexcept</argsstring>
        <name>operator *</name>
        <!-- ...snip... -->
      </memberdef>
```

Notice the space in `operator *`. My only hypothesis so far is that your file has `<name>operator*</name>`. Can you see if this might be the issue and then we can go from there? Thanks!

**Comment by alandefreitas** [comment]
> Evan will look into this. But generally speaking, when we test with xsltproc they all need to be using the same version as what will be used to build the Boost release docs.

Yes. I agree.

I tried to investigate this further by updating or downgrading `xsltproc`. This is the `xsltproc --version` output:

Ubuntu 20:

```console
Using libxml 20910, libxslt 10134 and libexslt 820
xsltproc was compiled against libxml 20910, libxslt 10134 and libexslt 820
libxslt 10134 was compiled against libxml 20910
libexslt 820 was compiled against libxml 20910
```

Ubuntu 22:

```console
Using libxml 20913, libxslt 10134 and libexslt 820
xsltproc was compiled against libxml 20913, libxslt 10134 and libexslt 820
libxslt 10134 was compiled against libxml 20913
libexslt 820 was compiled against libxml 20913
```

The message is not very straightforward and I couldn't find a way to upgrade/downgrade it. I think it's just not something people do very often. But I'll have a better look.

Assuming `xsltproc` is really the problem, this problem is going to become more and more common as people and the VMs in CI update Ubuntu.

**Comment by alandefreitas** [comment]
> Can you look at the contents of classboost_1_1urls_1_1pct__string__view.xml

Checking.

**Comment by evanlenz** [comment]
If my hypothesis is correct, then xsltproc is a complete red herring, because the difference occurs far upstream. But we'll see, based on what you find in that file!

**Comment by alandefreitas** [comment]
> it appears that the output of Doxygen is what will dictate whether you get one or two underscores

I think you are right. I believe Ubuntu 22 comes with doxygen 1.9.1 (`sudo apt install -y doxygen`) and `b2` wasn't picking up the `/usr/local/` version installed from `https://github.com/doxygen/doxygen.git#Release_1_8_15`. I get different results when I purge doxygen  1.9.1. 

<details>
  <summary>Ubuntu 22 + doxygen 1.9.1 (sudo apt install -y doxygen)</summary>

```console
$ doxygen --version
1.9.1
```

```xml
<memberdef kind="function" id="classboost_1_1urls_1_1pct__string__view_1a8f4e46a6c00359c82fd29b601c556191" prot="public" static="no" const="yes" explicit="no" inline="yes" noexcept="yes" virt="non-virtual">
        <type><ref refid="classboost_1_1urls_1_1decode__view" kindref="compound">decode_view</ref></type>
        <definition>decode_view boost::urls::pct_string_view::operator*</definition>
        <argsstring>() const noexcept</argsstring>
        <name>operator*</name>
        <briefdescription>
<para>Return the string as a range of decoded characters. </para>
        </briefdescription>
        <detaileddescription>
<para><simplesect kind="par"><title>Complexity</title><para>Constant.</para>
</simplesect>
<simplesect kind="par"><title>Exception Safety</title><para>Throws nothing.</para>
</simplesect>
<simplesect kind="see"><para><ref refid="classboost_1_1urls_1_1decode__view" kindref="compound">decode_view</ref>. </para>
</simplesect>
</para>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="libs/url/include/boost/url/pct_string_view.hpp" line="305" column="5" bodyfile="libs/url/include/boost/url/decode_view.hpp" bodystart="539" bodyend="542"/>
      </memberdef>
```
</details>

<details>
  <summary>Ubuntu 22 + doxygen 1.8.15 (https://github.com/doxygen/doxygen.git#Release_1_8_15)</summary>


```console
$ doxygen --version
1.8.15
```

```xml
<memberdef kind="function" id="classboost_1_1urls_1_1pct__string__view_1ad625af7f8285fe3d9150a715111d86c3" prot="public" static="no" const="yes" explicit="no" inline="yes" virt="non-virtual">
        <type><ref refid="classboost_1_1urls_1_1decode__view" kindref="compound">decode_view</ref></type>
        <definition>decode_view boost::urls::pct_string_view::operator *</definition>
        <argsstring>() const noexcept</argsstring>
        <name>operator *</name>
        <briefdescription>
<para>Return the string as a range of decoded characters. </para>
        </briefdescription>
        <detaileddescription>
<para><simplesect kind="par"><title>Complexity</title><para>Constant.</para>
</simplesect>
<simplesect kind="par"><title>Exception Safety</title><para>Throws nothing.</para>
</simplesect>
<simplesect kind="see"><para><ref refid="classboost_1_1urls_1_1decode__view" kindref="compound">decode_view</ref>. </para>
</simplesect>
</para>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="libs/url/include/boost/url/pct_string_view.hpp" line="305" column="1" bodyfile="libs/url/include/boost/url/decode_view.hpp" bodystart="539" bodyend="542"/>
      </memberdef>
```

</details>

<details>
  <summary>Ubuntu 20</summary>


```console
$ doxygen --version
1.8.15
```

```xml
<memberdef kind="function" id="classboost_1_1urls_1_1pct__string__view_1ad625af7f8285fe3d9150a715111d86c3" prot="public" static="no" const="yes" explicit="no" inline="yes" virt="non-virtual">
<type>
<ref refid="classboost_1_1urls_1_1decode__view" kindref="compound">decode_view</ref>
</type>
<definition>decode_view boost::urls::pct_string_view::operator *</definition>
<argsstring>() const noexcept</argsstring>
<name>operator *</name>
<briefdescription>
<para>Return the string as a range of decoded characters. </para>
</briefdescription>
<detaileddescription>
<para>
<simplesect kind="par">
<title>Complexity</title>
<para>Constant.</para>
</simplesect>
<simplesect kind="par">
<title>Exception Safety</title>
<para>Throws nothing.</para>
</simplesect>
<simplesect kind="see">
<para>
<ref refid="classboost_1_1urls_1_1decode__view" kindref="compound">decode_view</ref>
.
</para>
</simplesect>
</para>
</detaileddescription>
<inbodydescription> </inbodydescription>
<location file="libs/url/include/boost/url/pct_string_view.hpp" line="305" column="1" bodyfile="libs/url/include/boost/url/decode_view.hpp" bodystart="539" bodyend="542"/>
</memberdef>
```

</details>

In a way, this is a similar problem as more and more people upgrade to doxygen 1.9.1.

**Pull request merged**
