### PR TITLE
magnet uses StringToken

### LINKED ISSUE #535: magnet uses StringToken
_MutableString_ is being removed

### PR DESCRIPTION
**Pull request by alandefreitas**
fix #535

### CODE REVIEW

**Comment by alandefreitas** [comment]
I believe the new rules for query/params_ref broke something with magnet.  For instance,

```cpp
    auto xt = m.exact_topics();
    for (auto h : xt)
        std::cout << "topic: " << h << "\n";
```

is now creating a url_view to the wrong address, even before removing MutableString, but I still not being able to figure out why.

**Comment by alandefreitas** [comment]
> I believe the new rules for query/params_ref broke something with magnet. 

That suspicion was correct. The old interface that returned string views cannot work anymore because params return references to temporary strings that don't exist after the view is dereferenced.

**Comment by vinniefalco** [comment]
good to go if you think its ready

**Comment by alandefreitas** [comment]
Merged

**Pull request closed without merging**
