### PR TITLE
Drone cache

### PR DESCRIPTION
**Pull request by alandefreitas**

### CODE REVIEW

**Comment by alandefreitas** [comment]
@sdarwin 

https://drone.cpp.al/boostorg/url/2102/1/4

```
level=error name=drone-cache ts=2023-03-03T22:45:49.464797598Z caller=main.go:628 
err="[IMPORTANT] build cache, rebuild failed, upload from <cache> to 
<url/boostorg-url-develop-amd64-cppalliance-droneubuntu2204-1/cache>, rebuilder 
rebuild put file, upload file, pipe reader failed, storage backend put failure, put the object, 
NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose
 messaging see aws.Config.CredentialsChainVerboseErrors\n"
```

**Comment by sdarwin** [comment]
@alandefreitas the API keys were enabled on the CPPAlliance account only.     Ok, now added to boostorg.

**Comment by sdarwin** [comment]
Don't merge the pr yet. I have at least one possible change planned, switch "mount" to "mounts", a list.

**Comment by alandefreitas** [comment]
> the API keys were enabled on the CPPAlliance account only

Could you enable it for `alandefreitas` too so I can test these kinds of changes?

> Don't merge the pr yet. 

I merged the one in boostservertech already. I was replicating it for boost.url because `drone.sh` needs some adjustments and boost.url ends up being the "source of truth" for the generator.

>  switch "mount" to "mounts", a list.

Ok. Let me know if I have to change anything in the generator. I guess the environment variable might need to change to a comma-separated list or something.

**Comment by sdarwin** [comment]
Enabled on `alandefreitas` with organization secret.

**Comment by sdarwin** [comment]
@alandefreitas - 'drone_cache_mount' has been modified to support a comma separated list of mount points. The name stayed the same since the plugin itself uses the terminology "mount". 

When using one directory, no change is required.  With multiple directories, the new feature is available.

**Comment by alandefreitas** [comment]
`restore-cache` keeps failing:

```
level=error name=drone-cache ts=2023-03-06T17:57:46.332474138Z caller=main.go:628 err="[IMPORTANT] restore cache, restore failed, download from <url/boostorg-url-develop-amd64-cppalliance-droneubuntu2204-1/cache> to <cache>, extract files from downloaded archive, pipe reader failed, tar reader <get file from storage backend, pipe writer failed, storage backend get failure, get the object, NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: WWD8M384281977MV, host id: HXBfH/q9t1wVk/k43Sa+1n9uzlyoUGHiV4M07x8UpLwEji+cqwjGccNLsLIOk9hC8/fwjrSMHaI=>, archive not readable\n"
```

I'm not sure the cached path of the script is working because `restore-cache` always fails so there's never a `cache` directory in the `Everything` step.

**Comment by sdarwin** [comment]
@alandefreitas When I tried a similar command locally, xargs needed a --null flag:

```
xargs -I{} --null
```

**Pull request merged**
