### PR TITLE
Added links to helpcard.svg

### PR DESCRIPTION
**Pull request by klemens-morgenstern**
Not sure I got the rel-link right, but let's hope.

This lack of links keeps frustrating me.

### CODE REVIEW

**Comment by klemens-morgenstern** [comment]
Second version seems to work, with weird iframe behaviour though. I reckon better than nothing.

**Comment by alandefreitas** [comment]
I think the links when inside the card in the rendered HTML, lead to the page inside an `iframe`, which is kind of weird and not very useful.

image

**Comment by vinniefalco** [comment]
The Help Card is meant to be printed out, otherwise the user can just go to the corresponding Refrence page. For example:
https://www.boost.org/doc/libs/master/libs/url/doc/html/url/ref/boost__urls__url_view.html

**Comment by klemens-morgenstern** [comment]
It maybe mean to be this way, but I keep using it in a browser being frustrated that I can't click it.

**Comment by alandefreitas** [comment]
> I can't click it.

But now you can click it but the browser doesn't take you to the right place. It updates the iframe.

**Comment by klemens-morgenstern** [comment]
Fixed the iframe issue, links for correctly now.

**Comment by vinniefalco** [comment]
None of these seem to work:

image

Also, the link is not underlined on hover

**Comment by klemens-morgenstern** [comment]
oh, the set functions can of course not point to url_view

**Comment by alandefreitas** [comment]
Is this good to go? 

Is Vinnie's request ("Also, the link is not underlined on hover") achievable?

**Comment by alandefreitas** [comment]
OK. So going through the links:

Missing links:
- `set_scheme_id`

Broken links:
- `remove_scheme`
- `normalize_scheme`
- `remove_userinfo`
- `remove_password`
- `remove_port`
- `normalize_path`
- `remove_query`
- `normalize_query`
- `remove_fragment`
- `normalize_fragment`
- `remove_authority`
- `remove_origin`
- All free functions in "Other"

Most (or all) broken links just need to refer to `url` rather than `url_view`. The free functions in "Other" are also broken because they are trying to refer to member functions in `url_view`.

**Comment by alandefreitas** [comment]
Stale?

**Pull request closed without merging**
