### PR TITLE
Removed unused variable

### PR DESCRIPTION
**Pull request by BrianWeed**
'buf' is unused here

### CODE REVIEW

**Comment by alandefreitas** [comment]
@sdarwin the "CI / Runner Selection" step got stuck again (already restarted).

**Comment by sdarwin** [comment]
@alandefreitas , that means the issue has escalated in some way.   The first time this happened it seemed to be an isolated event.  But now it is repeating, so needs to be investigated more.

There was a job missing runners since yesterday.   That was the problem.

When you restarted the workflow today, it would launch one runner for the selection process. And yesterday's job would steal it.

A work-around would be to view what's happening in the Actions page.   Completely cancel a failing workflow which is missing a few runners.    Then, restart the new workflow from today.   Of course, not ideal.   4

Perhaps always-on permanent instances could be launched (drone has that), but it increases costs and complexity, if done per-repo.

Something else: ubuntu-latest may still be ubuntu-22.04.  Therefore, to install the newest gcc, specify ubuntu-24.04.   It's safer to not depend on `latest`, but specify the required OS tag.

**Comment by sdarwin** [comment]
The philips terraform runners are far from perfect in terms of the documentation, and also design.   I have discovered this variable:

`minimum_running_time_in_minutes: 5 (default) `

If an autoscaled instance fails to complete launch within 5 minutes, it is scaled down.

And yet, that was happening, and you'd even expect it, because of the extensive amount of the software involved in a launching an ec2 instance. It needs to upgrade the github runner package, etc.

Increased number to 15 minutes.  

Theoretically the bug is fixed now.

**Comment by alandefreitas** [comment]
@sdarwin OK. I'll keep restarting until it works.

**Comment by sdarwin** [comment]
> @sdarwin OK. I'll keep restarting until it works.

Again, "theoretically the bug is fixed now."    The recent problem was caused by losing runners due to a 5 minute timeout.   By setting this to 15 minutes, the runners should not be lost.     DM me in Slack if the same issue continues.

**Pull request merged**
