### PR TITLE
enable pedantic warnings in tests

### LINKED ISSUE #627: urls::string_token::arg struct has virtual functions but not virtual destructor
On MSVC 17, Using this library git tag `boost-1.81.0.beta1`, boost-1.80.0 (installed via conan) and this library (installed with CMake-FetchContent) I ran into a compiler error when I had elevated warning [C4265 Virtual class missing virtual destructor](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4265?view=msvc-170) to error. 

main.cpp
```
#include <boost/url/url.hpp>

int main()
{
  boost::urls::url url("http://boost.org");
  return 0;
}
```

CMakeLists.txt
```
CMAKE_MINIMUM_REQUIRED(VERSION 3.15)

project(use_boost_url)

find_package(Boost REQUIRED)
include(FetchContent)
FetchContent_Declare(boost_url_copy
  GIT_REPOSITORY https://github.com/boostorg/url.git
  GIT_TAG boost-1.81.0.beta1
  GIT_SHALLOW 1
  )
FetchContent_MakeAvailable(boost_url_copy)

add_library(demo main.cpp)
target_link_libraries(demo Boost::url)

# promote virtual class without virtual destructor to error
# https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4265?view=msvc-170
target_compile_options(demo PUBLIC /we4265)
```
conanfile.txt
```
[requires]
boost/1.80.0

[generators]
CMakeDeps
CMakeToolchain
````

conan install and cmake configure including some output to show compiler version
```
>mkdir build && cd build
>conan install .. -s build_type=Release -s compiler="Visual Studio" -s compiler.version=17 -s arch=x86_64 --build=missing
>cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake 
-- Building for: Visual Studio 17 2022
-- Using Conan toolchain: C:/Users/User/repos/use_boost_url/build/conan_toolchain.cmake
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
-- The C compiler identification is MSVC 19.33.31630.0
-- The CXX compiler identification is MSVC 19.33.31630.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped
```

Build output
```
\build>cmake --build . --config Release
MSBuild version 17.3.1+2badb37d1 for .NET Framework
  Checking File Globs
  Checking Build System
  Building Custom Rule C:/Users/User/repos/use_boost_url/build/_deps/boost_url_copy-src/CMakeLists.txt
  src.cpp
  boost_url.vcxproj -> C:\Users\User\repos\use_boost_url\build\_deps\boost_url_copy-build\Release\boost_url.lib
  Building Custom Rule C:/Users/User/repos/use_boost_url/CMakeLists.txt
  main.cpp
C:\Users\User\repos\use_boost_url\build\_deps\boost_url_copy-src\include\boost/url/grammar/string_token.hpp(137,1): error C4265: 'boost::ur
ls::string_token::return_string': class has virtual functions, but its non-trivial destructor is not virtual; instances of this class may n
ot be destructed correctly [C:\Users\User\repos\use_boost_url\build\demo.vcxproj]
```

### PR DESCRIPTION
**Pull request by alandefreitas**
fix #627

### CODE REVIEW

**Comment by pdimov** [comment]
`warnings=extra` already turns on `/W4` on msvc and `-Wall -Wextra` on clang.

**Comment by pdimov** [comment]
Also, it's not possible to copy or assign or slice an abstract class, so all the "prevent misuse" things are unnecessary. The destructor just needs to be made protected to avoid the warning (https://godbolt.org/z/jE5Mxss95).

**Comment by alandefreitas** [comment]
@wilhelm-now, could you check if that works locally for you? I can't replicate the error [in CI](https://github.com/boostorg/url/actions/runs/3492481941/jobs/5846310777).

@grisumbras @pdimov, do you have any other ideas to replicate the error? It looks like [`<toolset>msvc:<cxxflags>"/W4"`](https://github.com/alandefreitas/url/blob/7ddf962e61249cd54a939828e366420eb87955f1/test/Jamfile#L20) is not enough and drone has [no other flags](https://github.com/alandefreitas/url/blob/7f44da491b1dbc831551db9db8301a4bbc9a866a/.drone.star#L110) to override "/W4".

**Comment by wilhelm-now** [comment]
@alandefreitas I checked lastest develop after merge (commit 1d87343ea756b669baf836914d4b1d78cdba5ddb) and could no longer reproduce the issue. Thank you!

**Pull request merged**
